### ISSUE TITLE
composer安装失败

### ISSUE THREAD

**Issue by studentcaoqc** [DongyunLee/SM3-PHP#1]
require 'vendor/autoload.php';

use SM3\SM3;

$sm3 = new SM3('abc');
echo $sm3;
这边报错引用不到require 'vendor/autoload.php';
请问一下，这个是引用Composer 的吗

**Comment by studentcaoqc** [comment]
Fatal error: Class 'SM3\SM3' not found in E:\xuexi\SM3-PHP-master\demo.php on line 14
这个是执行demo的报错信息

**Comment by studentcaoqc** [comment]
第14 行 $sm3 = new SM3('abc');

**Comment by DongyunLee** [comment]
> require 'vendor/autoload.php';
> use SM3\SM3;
> $sm3 = new SM3('abc');
> echo $sm3;
> 这边报错引用不到require 'vendor/autoload.php';
> 请问一下，这个是引用Composer 的吗

对没错，是引用 `composer` 的，发现之前没有传到 `composer` 上，现已修复，可通过访问 [Packagist](https://packagist.org/packages/ch4o5/sm3-php) 进行查看。

README 中的示例也进行了更新，现在的安装方式是：
```shell
composer require ch4o5/sm3-php
```
然后再在文件中进行 `autoload.php` 文件的引入，和 `SM3\SM3()` 的调用。

在马上的 1.1 版本中，会提取出来一些语法糖，比如直接通过函数 `sm3()` 而不是实例化类、长二进制的按位与、或、非、异或、加运算等。

感谢关注！
