### ISSUE TITLE
经测试V1.1.2, V1.1.1结果有误, demo结果也不同

### ISSUE THREAD

**Issue by mCloud** [DongyunLee/SM3-PHP#10]
环境:
debian 7.8
PHP 5.4.45-0+deb7u11 (cli) (built: Aug 30 2017 01:07:33) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

下载release V1.1.2, V1.1.1 访问demo.php
计算结果均为: 183920f00e15a0433ee3a8fc90dd9ac164c4142ccf63ca189a8f645ec96ff8de
正确结果为: 66c7f0f462eeedd9d1f2d46bdc10e4e24167c4875cf2f7a2297da02b8f4ba8e0

下载部署V1.1 , 复制V1.1.2的demo.php 访问可以得到预期结果.  是否高版本引入了问题?

**Comment by DongyunLee** [comment]
感谢测试！
可以试试最新的master分支中是否解决了这个问题：
```bash
composer require ch4o5/sm3-php dev-master
```

欢迎随时反馈～

**Comment by DongyunLee** [comment]
长时间没有回复，先关了

**Comment by DongyunLee** [comment]
v1.1.3 版本已发布，本问题已在新版本中解决，现在可直接通过 composer 进行更新。

> 短期内暂时不会有其他版本的更新和维护

感谢关注！
