### ISSUE TITLE
为啥我这边输出结果不一致

### ISSUE THREAD

**Issue by vitoland** [DongyunLee/SM3-PHP#22]
https://github.com/DongyunLee/SM3-PHP/blob/fad1211c0d1f21a26a53e5591b790690489108c5/examples/sm3_file/sm3_file.php#L18

我这边是 `2daef60e7a0b8f5e024c81cd2ab3109f2b4f155cf83adeb2ae5532f74a157fdf`
本地 远程都是 `echo sm3_file('https://raw.githubusercontent.com/DongyunLee/SM3-PHP/master/examples/sm3_file/test.txt');`

测试服务器信息 **************

**Comment by DongyunLee** [comment]
这个还有问题，ci一直没跑过，最近工作忙暂时还没时间修复

**Comment by DongyunLee** [comment]
`sm3_file()` 的逻辑其实很简单，就是把文件 `file_get_contents()` 出来，然后再跑 `sm3()` 方法，你可以先按这个步骤解耦自测一下~

不过暂时不推荐用 `sm3_file()` 这个方法进行文件的摘要算法，因为底层逻辑的问题，图片什么的很容易就会内存溢出，所以 **务必 慎用！**

**Comment by DongyunLee** [comment]
我暂时先 revert 到没有 `sm3_file` 的版本了，我忙完这一阵了抽空更新下，可以先用着 `sm3` 方法
